# Generated by Django 5.2.16 on 2026-07-30 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.BinaryField(db_index=True, max_length=65535, validators=[django.core.validators.MaxLengthValidator(65535)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='unique_inline_symbol')],
            },
        ),
        migrations.CreateModel(
            name='TermSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.symbol')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('term', 'order'), name='unique_symbol_order_per_term')],
            },
        ),
    ]
