# Generated by Django 5.2.16 on 2026-07-30 01:13

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salt', models.BinaryField(default=core.models.rnd32)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salt', models.BinaryField(default=core.models.rnd32)),
                ('root_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_keys', to='core.rootkey')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('symbol', models.BinaryField(db_index=True, max_length=65535, null=True, validators=[django.core.validators.MaxLengthValidator(65535)])),
                ('file', models.FileField(db_index=True, editable=False, max_length=255, null=True, upload_to='symbol/')),
                ('system_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='core.systemkey')),
            ],
        ),
        migrations.CreateModel(
            name='TermSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mutation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='term_symbol_mutations', to='core.symbol')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.symbol')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol__isnull', False), ('system_key__isnull', True)), fields=('symbol',), name='unique_clear_inline_symbol'),
        ),
        migrations.AddConstraint(
            model_name='termsymbol',
            constraint=models.UniqueConstraint(fields=('term', 'order'), name='unique_symbol_order_per_term'),
        ),
    ]
