# Generated by Django 5.2.16 on 2026-07-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature_c', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('pressure_hpa', models.FloatField()),
                ('gas_resistance_ohms', models.FloatField(blank=True, null=True)),
                ('air_quality_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
    ]
