# Generated by Django 5.2.16 on 2026-07-30 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreading',
            name='source',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('demo', 'Demo')], db_index=True, default='sensor', max_length=12),
        ),
        migrations.AlterField(
            model_name='environmentalreading',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
