# Generated by Django 5.2.16 on 2026-07-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('measurements', '0002_environmentalreading_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreading',
            name='semantic_term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='environmental_reading', to='core.term'),
        ),
    ]
