# Generated by Django 5.2.16 on 2026-07-30 01:30

import struct
from datetime import timedelta, timezone

from django.db import migrations


EPOCH = __import__("datetime").datetime(1970, 1, 1, tzinfo=timezone.utc)


def encode_timestamp(value):
    delta = value.astimezone(timezone.utc) - EPOCH
    microseconds = (
        delta.days * 86_400_000_000
        + delta.seconds * 1_000_000
        + delta.microseconds
    )
    return struct.pack(">q", microseconds)


def create_term(Term, Symbol, TermSymbol, atoms):
    term = Term.objects.create()
    relations = []
    for order, atom in enumerate(atoms):
        symbol, _created = Symbol.objects.get_or_create(
            symbol=atom,
            system_key=None,
            defaults={"file": None},
        )
        relations.append(TermSymbol(term=term, symbol=symbol, order=order))
    TermSymbol.objects.bulk_create(relations)


def translate_readings(apps, schema_editor):
    Reading = apps.get_model("measurements", "EnvironmentalReading")
    Term = apps.get_model("core", "Term")
    Symbol = apps.get_model("core", "Symbol")
    TermSymbol = apps.get_model("core", "TermSymbol")
    old_symbol_ids = set()
    demo_index = 0

    for reading in Reading.objects.order_by("recorded_at").iterator(chunk_size=250):
        if reading.semantic_term_id:
            old_symbol_ids.update(
                TermSymbol.objects.filter(term_id=reading.semantic_term_id).values_list(
                    "symbol_id", flat=True
                )
            )
            old_term_id = reading.semantic_term_id
            reading.semantic_term_id = None
            reading.save(update_fields=("semantic_term",))
            Term.objects.filter(pk=old_term_id).delete()

        create_term(
            Term,
            Symbol,
            TermSymbol,
            (
                encode_timestamp(reading.recorded_at),
                struct.pack(">h", round(reading.temperature_c * 100)),
                struct.pack(">H", round(reading.relative_humidity * 100)),
                struct.pack(">I", round(reading.pressure_hpa * 100)),
            ),
        )

        should_assess = reading.air_quality_index is not None
        if reading.source == "demo":
            should_assess = should_assess and demo_index % 3 == 0
            demo_index += 1
        if should_assess:
            percentage = round(
                max(0, min(100, 100 - float(reading.air_quality_index) / 2))
            )
            observed_at = reading.recorded_at
            if reading.source == "demo":
                observed_at += timedelta(minutes=20)
            create_term(
                Term,
                Symbol,
                TermSymbol,
                (
                    encode_timestamp(observed_at),
                    struct.pack("B", percentage),
                    struct.pack("B", 0b00011111),
                ),
            )

    old_symbol_ids = list(old_symbol_ids)
    for offset in range(0, len(old_symbol_ids), 500):
        Symbol.objects.filter(
            pk__in=old_symbol_ids[offset : offset + 500],
            termsymbol__isnull=True,
            term_symbol_mutations__isnull=True,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('measurements', '0003_environmentalreading_semantic_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityAssessment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.term',),
        ),
        migrations.CreateModel(
            name='EnvironmentalObservation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.term',),
        ),
        migrations.RunPython(translate_readings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='EnvironmentalReading',
        ),
    ]
