# Generated by Django 5.2.16 on 2026-07-30 03:13

from django.db import migrations
from django.db.models import Count


def swap_pressure_and_humidity(apps, schema_editor):
    Term = apps.get_model("core", "Term")
    TermSymbol = apps.get_model("core", "TermSymbol")
    term_ids = (
        Term.objects.annotate(symbol_count=Count("termsymbol"))
        .filter(symbol_count=4)
        .values_list("pk", flat=True)
    )
    for term_id in term_ids.iterator(chunk_size=250):
        pressure = TermSymbol.objects.get(term_id=term_id, order=3)
        humidity = TermSymbol.objects.get(term_id=term_id, order=2)
        pressure.order = 4
        pressure.save(update_fields=("order",))
        humidity.order = 3
        humidity.save(update_fields=("order",))
        pressure.order = 2
        pressure.save(update_fields=("order",))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('measurements', '0004_airqualityassessment_environmentalobservation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalObservation',
        ),
        migrations.CreateModel(
            name='QuickCheck',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.term',),
        ),
        migrations.RunPython(
            swap_pressure_and_humidity,
            swap_pressure_and_humidity,
        ),
    ]
